# Generated by Django 4.2.4 on 2023-08-22 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ('tipo',), 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='nome',
            new_name='tipo',
        ),
    ]
